app/models.py
import datetime

from sqlalchemy.ext.hybrid import hybrid_property
from app import db


class Category(db.Model):
    __tablename__ = "categories"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    description = db.Column(db.Text)
    topics = db.relationship('Topic', backref="category", lazy=True)

    def __repr__(self):
        return '<Category: Title: {}>'.format(self.title)


class Topic(db.Model):
    __tablename__ = "topics"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=False)
    answers = db.relationship('Answer', backref="topic", lazy=True)

    parent_id = db.Column(db.Integer, db.ForeignKey('topics.id'))
    children = db.relationship("Topic", backref=db.backref('parent', remote_side=[id]))

    difficulty = db.Column(db.Float, default=0.3)
    days_between_reviews = db.Column(db.Float, default=1.0)
    date_last_reviewed = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def update_topic(self, performance_rating):
        waiting_progress = 0

        if performance_rating < 0.6:
            waiting_progress = 1
        else:
            waiting_progress = min(2, (datetime.datetime.utcnow() - self.date_last_reviewed).days/self.days_between_reviews)

        self.difficulty += waiting_progress * 1/17*(8-9*performance_rating)
        
        difficulty_weight = 3 - 1.7 * self.difficulty

        if performance_rating >= 0.6:
            self.days_between_reviews *= 1 + (difficulty_weight) * waiting_progress
        else:
            self.days_between_reviews *= 1 / pow(difficulty_weight,2)
        
        self.date_last_reviewed = datetime.datetime.utcnow()

        db.session.commit()
    
    @hybrid_property
    def waiting_progress(self):
        return min(2, (datetime.datetime.utcnow() - self.date_last_reviewed).days/self.days_between_reviews)
    
    def __repr__(self):
        return '<Topic: Title: {} Body: {}...>'.format(self.title, self.body[:10])


class Answer(db.Model):
    __tablename__ = "answers"

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    topic_id = db.Column(db.Integer, db.ForeignKey('topics.id'), nullable=False)
    time = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    performance_rating = db.Column(db.Float)

    def __repr__(self):
        return '<Answer: Topic id: {} Body: {}... Performance: {}>'.format(self.topic_id, self.body[:10], self.performance_rating)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FloatField, SubmitField
from wtforms.validators import DataRequired, NumberRange


class AnswerForm(FlaskForm):
    performance_rating = FloatField('Performance rating', validators=[NumberRange(min=0.0, max=1.0)])
    body = TextAreaField('Answer', validators=[DataRequired()])
    submit = SubmitField('Answer')


class TopicForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Topic body', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CategoryForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from config import Config

db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    from app.errors import bp as bp_errors
    app.register_blueprint(bp_errors)

    from app.main import bp as bp_main
    app.register_blueprint(bp_main)

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from datetime import datetime, timedelta
from app import db
from app.main import bp
from app.models import Category, Topic, Answer
from app.main.forms import AnswerForm, CategoryForm, TopicForm
from markdown import markdown

@bp.route('/', methods=['GET', 'POST'])
def index():
    categories = Category.query.all()

    form = CategoryForm()

    if form.validate_on_submit():
        category = Category(
            title=form.title.data,
            description=form.description.data
        )

        db.session.add(category)
        db.session.commit()

        flash("The category {} was added".format(category.title))

        return redirect(url_for('main.index'))

    return render_template('index.html', categories=categories, add_category_form=form)


@bp.route('/category/<int:id>', methods=['GET', 'POST'])
def category(id):
    category = Category.query.get_or_404(id)

    form = TopicForm()

    if form.validate_on_submit():
        topic = Topic(
            title=form.title.data,
            body=form.body.data,
            body_html=markdown(form.body.data),
            category_id=category.id
        )

        db.session.add(topic)
        db.session.commit()

        flash("The topic {} was to added to category {}".format(topic.title, category.title))

        return redirect(url_for('main.category', id=id))

    return render_template('category.html', category=category, add_topic_form=form)


@bp.route('/topic/<int:id>', methods=['GET', 'POST'])
def topic(id):
    current_topic = Topic.query.get_or_404(id)

    form = TopicForm()

    if form.validate_on_submit():
        sub_topic = Topic(
            title=form.title.data,
            body=form.body.data,
            body_html=markdown(form.body.data),
            category=current_topic.category,
            parent=current_topic
        )

        db.session.add(sub_topic)
        db.session.commit()

        flash("Sub-topic {} was added to topic {}".format(sub_topic.title, current_topic.title))

        return redirect(url_for('main.topic', id=id))

    return render_template('topic.html', topic=current_topic, add_child_topic_form=form)


@bp.route('/review')
def review():
    topics = Topic.query.all()

    topics.sort(key=lambda current_topic: current_topic.waiting_progress, reverse=True)

    return render_template('review.html', topics=topics[:25])


@bp.route('/review/<int:id>', methods=['GET', 'POST'])
def review_topic(id):
    topic = Topic.query.get_or_404(id)

    form = AnswerForm()

    if form.validate_on_submit():
        topic.update_topic(form.performance_rating.data)

        answer = Answer(
            topic=topic,
            body=form.body.data,
            body_html=markdown(form.body.data)
        )

        db.session.add(answer)
        db.session.commit()
        flash("You answered the topic {} and gave yourself the performance rating {}".format(
            topic.title, answer.performance_rating)
        )

        return redirect(url_for('main.answer', id=answer.id))

    return render_template('review_topic.html', topic=topic, answer_form=form)


@bp.route('/answer/<int:id>', methods=['GET', 'POST'])
def answer(id):
    answer = Answer.query.get_or_404(id)

    form = AnswerForm()

    if form.validate_on_submit():
        answer.performance_rating = form.performance_rating.data
        db.session.commit()

        return redirect(url_for('main.review'))

    return render_template('answer.html', answer=answer, form=form)

app/templates/answer.html
{% extend 'index.html' %}

{%  block content %}
    <div class="add-box rating">
        <h3>Rate your answer [0;1]</h3>
        <form class="form-group" action="" method="post">
            {{ answer_form.hidden_tag() }}
            <div class="form-group">
                {{ answer_form.performance_rating.label }}
                {{ answer_form.performance_rating(class="form-control") }}
                {% for error in answer_form.performance_rating.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div>{{ answer_form.submit(class="btn btn-outline-success") }}</div>
        </form>
    </div>

    <div class="topic">
        <h1>{{ answer.topic.title }}</h1>
    </div>

    <div class="answer-vs-body">
        <div class="body">
            {{ answer.topic.body_html|safe }}
        </div>
        <div class="answer">
            {{ answer.body_html|safe }}
        </div>
    </div>

{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <title>Rememory</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Rememory</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.review') }}">Review</a>
          </li>
        </ul>
      </div>
    </nav>


    <div class="container" style="padding-top: 20px;">
        {%  block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/category.html
{% extends 'base.html' %}

{% block content %}
    <div class="controls">
        <div>
            <h1>{{ category.title }}</h1>
            <p>{{ category.description }}</p>
        </div>
        <div class="text-right" style="color: white;">
            <a style="color: white;" class="btn btn-primary">Edit</a>
            <a class="btn btn-danger">Delete</a>
        </div>
    </div>

    <!-- TODO: Figure out how to recursively render topics. -->
    <div class="topic-list">
        {% for topic in category.topics recursive %}
            <div class="topic-item">
                <h3><a href="{{ url_for('main.topic', id=topic.id) }}">{{ topic.title }}</a></h3>
                <p>{{ topic.body_html|safe }}</p>
                {% if topic.children %}
                    <div class="topic-child-item">
                        {{ loop(topic.children) }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    <div class="add-topic-to-category add-box">
        <h3>Add topic to {{ category.title }}</h3>
        <form class="form-group" action="" method="post">
            {{ add_topic_form.hidden_tag() }}
            <div class="form-group">
                {{ add_topic_form.title.label }}
                {{ add_topic_form.title(class="form-control") }}
                {% for error in add_topic_form.title.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ add_topic_form.body.label }}
                {{ add_topic_form.body(rows=10, class="form-control") }}
                {% for error in add_topic_form.body.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div>{{ add_topic_form.submit(class="btn btn-outline-success") }}</div>
        </form>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="list row">
    {% for category in categories %}
        <div class="list-item col-4">
            <div class="title">
                <h1><a href="{{ url_for('main.category', id=category.id) }}">{{ category.title }}</a></h1>
            </div>
            <div class="description">
                <p>{{ category.description }}</p>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="add-category add-box">
        <h3>Add new category</h3>
        <form class="form-group" action="" method="post">
            {{ add_category_form.hidden_tag() }}
            <div class="form-group">
                {{ add_category_form.title.label }}
                {{ add_category_form.title(class="form-control") }}
                {% for error in add_category_form.title.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ add_category_form.description.label }}
                {{ add_category_form.description(class="form-control") }}
                {% for error in add_category_form.description.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div>{{ add_category_form.submit(class="btn btn-outline-success") }}</div>
        </form>
    </div>
{% endblock %}

app/templates/review.html
{% extends 'base.html' %}

{% block content %}
    <div class="review-list">
    <h1>Review list</h1>
    <p>This is your review list. Please take some time to review the topics.</p>
    {% for topic in topics %}
        <div class="review-item">
            <p>Overdue indicator: <b>{{ topic.waiting_progress }}</b></p>
            <h3><a href="{{ url_for('main.review_topic', id=topic.id) }}">{{ topic.title }}</a></h3>
        </div>
    {% endfor %}
    </div>

{% endblock %}

app/templates/review_topic.html
{% extends 'base.html' %}

{% block content %}
    {{ topic.title }}
    <div class="answer-topic add-box">
        <form class="form-group" action="" method="post">
            {{ answer_form.hidden_tag() }}
            <div class="form-group">
                {{ answer_form.performance_rating.label }}
                {{ answer_form.performance_rating(class="form-control") }}
                {% for error in answer_form.performance_rating.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ answer_form.body.label }}
                {{ answer_form.body(class="form-control") }}
                {% for error in answer_form.body.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div>{{ answer_form.submit(class="btn btn-outline-success") }}</div>
        </form>
    </div>
{% endblock %}

app/templates/topic.html
{% extends 'base.html' %}

{% block content %}
    {% if topic.parent %}
        <p>Parent topic: <a href="{{ url_for('main.topic', id=topic.parent.id) }}">{{ topic.parent.title }}</a></p>
    {% else %}
        <p>Category: <a href="{{ url_for('main.category', id=topic.category_id) }}">{{ topic.category.title }}</a></p>
    {% endif %}

    <div class="controls">
        <div>
            <h1>{{ topic.title }}</h1>
        </div>
        <div class="text-right">
            <a style="color: white;" class="btn btn-primary">Edit</a>
            <a style="color: white;" class="btn btn-danger">Delete</a>
        </div>

    </div>

    <div class="body">
        <p>{{ topic.body_html|safe }}</p>
    </div>

    <div class="topic-list">
    {% for child in topic.children recursive %}
        <div class="topic-item">
            <h3><a href="{{ url_for('main.topic', id=child.id) }}">{{ child.title }}</a></h3>
            <p>{{ child.body_html|safe }}</p>
            {% if child.children %}
                <div class="topic-child-item">
                    {{ loop(child.children) }}
                </div>
            {% endif %}
        </div>
    {% endfor %}
    </div>

    <div class="add-subtopic-to-topic add-box">
        <h3>Add sub topic to {{ topic.title }}</h3>
        <form class="form-group" action="" method="post">
            {{ add_child_topic_form.hidden_tag() }}
            <div class="form-group">
                {{ add_child_topic_form.title.label }}
                {{ add_child_topic_form.title(class="form-control") }}
                {% for error in add_child_topic_form.title.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ add_child_topic_form.body.label }}
                {{ add_child_topic_form.body(rows="10", class="form-control") }}
                {% for error in add_child_topic_form.body.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div>{{ add_child_topic_form.submit(class="btn btn-outline-success") }}</div>
        </form>
    </div>

    <div class="answers">
    {% for answer in topic.answers %}
        <div class="answer-item">
            <p>{{ answer.time }}<e>{{ answer.performance_rating }}</e></p>
            <p>{{ answer.body }}</p>
        </div>
    {% endfor %}
    </div>

    <div class="topic-facts text-right">
        <p>Last reviewed on:<br/> <b>{{ topic.date_last_reviewed }}</b></p>
        <p>Days between reviews:<br/> <b>{{ topic.days_between_reviews }}</b></p>
        <p>Difficulty:<br> <b>{{ topic.difficulty }}</b></p>
    </div>


{% endblock %}